/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package game.gui;

/**
 *
 * @author User
 */
public class MenuIniziale extends javax.swing.JPanel {

    private GestoreComponenti gestore;
    /**
     * Creates new form MenuIniziale
     */
    public MenuIniziale() {
        initComponents();
        
        PannelloSfondo sfondo = (PannelloSfondo) pnlSfondo;
        
        //sfondo.setMinimumSize(new java.awt.Dimension(1024, 768));
        sfondo.setImmagineSfondo("/assets/Menu.png");
        
        // Sposta i bottoni dal pannello principale dentro lo sfondo
        this.remove(btnNuovapartita);
        this.remove(btnCaricapartita);
        this.remove(btnEsci);
        
        gestore = new GestoreComponenti(sfondo);
        gestore.registra(btnNuovapartita, 450, 590, 410, 80);
        gestore.registra(btnCaricapartita, 450, 695, 410, 80);
        gestore.registra(btnEsci, 450, 790, 410, 80);
        
        // Riposiziona tutto quando la finestra cambia dimensione
        sfondo.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent evt) {
            //riposizionaBottoni(sfondo);
        }
        });
    }
    
    /*private static final int BTN_W = 410;
    private static final int BTN_H = 75;
    
    private void riposizionaBottoni(progetto.gioco.gui.PannelloSfondo sfondo) {
    java.awt.Rectangle area = sfondo.getAreaImmagine();

    // Scala le dimensioni del bottone in base al ridimensionamento dell'immagine
    double scalaX = (double) area.width / 1672.0;
    double scalaY = (double) area.height / 941.0;

    int btnW = (int) (BTN_W * scalaX);
    int btnH = (int) (BTN_H * scalaY);

    posizionaBottone(btnNuovapartita, area, 400, 490, btnW, btnH, scalaX, scalaY);
    posizionaBottone(btnCaricapartita, area, 400, 575, btnW, btnH, scalaX, scalaY);
    posizionaBottone(btnEsci, area, 400, 660, btnW, btnH, scalaX, scalaY);
}
    //btnOpzioni.setBounds((int)(w * 0.5 - btnW/2), (int)(h * 0.6), btnW, btnH);
    //btnEsci.setBounds((int)(w * 0.5 - btnW/2), (int)(h * 0.7), btnW, btnH);

    private void posizionaBottone(javax.swing.JButton btn, java.awt.Rectangle area,
                                int centroXimg, int centroYimg,
                                int btnW, int btnH, double scalaX, double scalaY) {
    int px = area.x + (int) (centroXimg * scalaX) - btnW / 2;
    int py = area.y + (int) (centroYimg * scalaY) - btnH / 2;
    btn.setBounds(px, py, btnW, btnH);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuovapartita = new javax.swing.JButton();
        btnCaricapartita = new javax.swing.JButton();
        btnEsci = new javax.swing.JButton();
        pnlSfondo = new PannelloSfondo();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new java.awt.BorderLayout());

        btnNuovapartita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Nuovapartita.png"))); // NOI18N
        btnNuovapartita.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuovapartita.setMaximumSize(new java.awt.Dimension(410, 60));
        btnNuovapartita.setMinimumSize(new java.awt.Dimension(0, 0));
        btnNuovapartita.addActionListener(this::btnNuovapartitaActionPerformed);
        add(btnNuovapartita, java.awt.BorderLayout.LINE_END);

        btnCaricapartita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Caricapartita.png"))); // NOI18N
        btnCaricapartita.addActionListener(this::btnCaricapartitaActionPerformed);
        add(btnCaricapartita, java.awt.BorderLayout.PAGE_END);

        btnEsci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Esci.png"))); // NOI18N
        btnEsci.addActionListener(this::btnEsciActionPerformed);
        add(btnEsci, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout pnlSfondoLayout = new javax.swing.GroupLayout(pnlSfondo);
        pnlSfondo.setLayout(pnlSfondoLayout);
        pnlSfondoLayout.setHorizontalGroup(
            pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1384, Short.MAX_VALUE)
        );
        pnlSfondoLayout.setVerticalGroup(
            pnlSfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        add(pnlSfondo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuovapartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuovapartitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuovapartitaActionPerformed

    private void btnEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsciActionPerformed

    private void btnCaricapartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricapartitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCaricapartitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaricapartita;
    private javax.swing.JButton btnEsci;
    private javax.swing.JButton btnNuovapartita;
    private javax.swing.JPanel pnlSfondo;
    // End of variables declaration//GEN-END:variables

}